// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's DoorAI profile: name, phase, sector interest, education, contact fields and other stored preferences.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_appointments_default = defineTool2({
  name: "list_my_appointments",
  title: "List my appointments",
  description: "List the signed-in user's appointments with an advisor, ordered by scheduled time.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 25)."),
    upcoming_only: z.boolean().optional().describe("If true, only return appointments in the future.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, upcoming_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("appointments").select("*").eq("user_id", ctx.getUserId()).order("scheduled_at", { ascending: true }).limit(limit ?? 25);
    if (upcoming_only) q = q.gte("scheduled_at", (/* @__PURE__ */ new Date()).toISOString());
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-conversations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_conversations_default = defineTool3({
  name: "list_my_conversations",
  title: "List my conversations",
  description: "List the signed-in user's DoorAI conversations (id, title, updated_at) most-recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("conversations").select("id, title, created_at, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-conversation-messages.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_conversation_messages_default = defineTool4({
  name: "get_conversation_messages",
  title: "Get conversation messages",
  description: "Fetch messages (role, content, created_at) from one of the signed-in user's DoorAI conversations. RLS restricts access to the user's own conversations.",
  inputSchema: {
    conversation_id: z3.string().uuid().describe("Conversation id to fetch messages for."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max messages (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data: conv, error: convErr } = await sb.from("conversations").select("id").eq("id", conversation_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (convErr) return { content: [{ type: "text", text: convErr.message }], isError: true };
    if (!conv) {
      return {
        content: [{ type: "text", text: "Conversation not found for this user." }],
        isError: true
      };
    }
    const { data, error } = await sb.from("messages").select("id, role, content, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: true }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "euvisntlxhzlgdwxcndo";
var mcp_default = defineMcp({
  name: "doorai-mcp",
  title: "DoorAI",
  version: "0.1.0",
  instructions: "Tools for the DoorAI Rotterdam education-transition app. Read the signed-in user's profile, appointments with an advisor, and DoorAI conversations. All access is scoped to the authenticated user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_my_appointments_default,
    list_my_conversations_default,
    get_conversation_messages_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
